//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbstractFileFormat
    {
        public int AbstractFileFormatId { get; set; }
        public double LineSpacing { get; set; }
        public int FontNameId { get; set; }
        public int ConferenceId { get; set; }
        public int AlignmentId { get; set; }
        public float FontSize { get; set; }
        public double Margin_Top { get; set; }
        public double Margin_Bottom { get; set; }
        public double Margin_Left { get; set; }
        public double Margin_Right { get; set; }
    
        public virtual Alignment Alignment { get; set; }
        public virtual Conference Conference { get; set; }
        public virtual FontName FontName { get; set; }
    }
}
