//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        public int AttendeeId { get; set; }
        public int ConferenceId { get; set; }
        public int FeeId { get; set; }
        public int UserId { get; set; }
        public int UserTypeId { get; set; }
        public System.DateTime RegDate { get; set; }
        public int PaymentStatusId { get; set; }
        public int PaymentAmount { get; set; }
        public string PaymentDetail { get; set; }
        public string ReceiptNumber { get; set; }
        public bool Delete { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual Fee Fee { get; set; }
        public virtual PaymentStatu PaymentStatu { get; set; }
        public virtual User User { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
