//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conference()
        {
            this.AbstractFileFormats = new HashSet<AbstractFileFormat>();
            this.Attendees = new HashSet<Attendee>();
            this.Contents = new HashSet<Content>();
            this.DateDealines = new HashSet<DateDealine>();
            this.Fees = new HashSet<Fee>();
            this.NotificationEmails = new HashSet<NotificationEmail>();
            this.Papers = new HashSet<Paper>();
            this.Reviewers = new HashSet<Reviewer>();
            this.ReviewItems = new HashSet<ReviewItem>();
            this.Topics = new HashSet<Topic>();
        }
    
        public int ConferenceId { get; set; }
        public string Username { get; set; }
        public string encryptedPassword { get; set; }
        public string Website { get; set; }
        public System.DateTime Date { get; set; }
        public string ContactName { get; set; }
        public string Contact { get; set; }
        public string PaperPrefix { get; set; }
        public bool LoggedIn { get; set; }
        public byte[] Logo { get; set; }
        public string Short_Name { get; set; }
        public string ChairmanName { get; set; }
        public string ChairmanEmail { get; set; }
        public string ConferencePhone { get; set; }
        public string SecretariatAddress { get; set; }
        public string ConferenceTime { get; set; }
        public string ConferenceVenue { get; set; }
        public bool Delete { get; set; }
        public string ConferenceName { get; set; }
        public string Fax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbstractFileFormat> AbstractFileFormats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendee> Attendees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DateDealine> DateDealines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee> Fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationEmail> NotificationEmails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paper> Papers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviewer> Reviewers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewItem> ReviewItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
