//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ContentId { get; set; }
        public string NewInfo { get; set; }
        public string WelcomeTitle { get; set; }
        public string WelcomeText { get; set; }
        public string Organizer { get; set; }
        public string Accomodation { get; set; }
        public string Committee { get; set; }
        public string CallForPapers { get; set; }
        public string Programmes { get; set; }
        public int ConferenceId { get; set; }
    
        public virtual Conference Conference { get; set; }
    }
}
