//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fee()
        {
            this.Attendees = new HashSet<Attendee>();
        }
    
        public int FeeId { get; set; }
        public string Category { get; set; }
        public string Currency { get; set; }
        public decimal EarlyBird { get; set; }
        public decimal Normal { get; set; }
        public int ConferenceId { get; set; }
        public string DisplayForNormal { get; set; }
        public string DisplayForEarlyBird { get; set; }
        public bool Delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendee> Attendees { get; set; }
        public virtual Conference Conference { get; set; }
    }
}
