//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConferenceDBEntities : DbContext
    {
        public ConferenceDBEntities()
            : base("name=ConferenceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AbstractFileFormat> AbstractFileFormats { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Alignment> Alignments { get; set; }
        public virtual DbSet<Attendee> Attendees { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DateDealine> DateDealines { get; set; }
        public virtual DbSet<EmailTag> EmailTags { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<FontName> FontNames { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<InvitationEmailStatu> InvitationEmailStatus { get; set; }
        public virtual DbSet<InvitationStatu> InvitationStatus { get; set; }
        public virtual DbSet<NotificationEmail> NotificationEmails { get; set; }
        public virtual DbSet<Paper> Papers { get; set; }
        public virtual DbSet<PaymentStatu> PaymentStatus { get; set; }
        public virtual DbSet<Reviewer> Reviewers { get; set; }
        public virtual DbSet<ReviewerType> ReviewerTypes { get; set; }
        public virtual DbSet<ReviewItem> ReviewItems { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
