//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        public int PaperId { get; set; }
        public int ConferenceId { get; set; }
        public int UserId { get; set; }
        public string PaperTitle { get; set; }
        public string AuthorList { get; set; }
        public string Affiliation { get; set; }
        public string Presenter { get; set; }
        public string Abstract { get; set; }
        public string PaperDescription { get; set; }
        public string AbstractFile { get; set; }
        public string Keywords { get; set; }
        public int TopicId { get; set; }
        public string AbstractSubmissionDate { get; set; }
        public int AbstractSubmissionNotification { get; set; }
        public string Prefix { get; set; }
        public string FullPaperFile { get; set; }
        public string CameraReadyPaperFile { get; set; }
        public string FullPaperSubmissionDate { get; set; }
        public string CameraReadyPaperSubmissionDate { get; set; }
        public int AbstractPaperStatus { get; set; }
        public int FullPaperStatus { get; set; }
        public int AbstractTotalNumberOfPages { get; set; }
        public int FullPaperTotalNumberOfPages { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
    }
}
