//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviewer
    {
        public int ReviewerId { get; set; }
        public int TitleId { get; set; }
        public int ReviewerTypeId { get; set; }
        public string ReviewerName { get; set; }
        public string Email { get; set; }
        public string Area { get; set; }
        public string Instituition { get; set; }
        public int InvitationStatusId { get; set; }
        public int InvitationEmailStatusId { get; set; }
        public int ConferenceId { get; set; }
        public bool Delete { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual InvitationEmailStatu InvitationEmailStatu { get; set; }
        public virtual InvitationStatu InvitationStatu { get; set; }
        public virtual ReviewerType ReviewerType { get; set; }
        public virtual Title Title { get; set; }
    }
}
