//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Venue { get; set; }
        public int TopicId { get; set; }
    
        public virtual Topic Topic { get; set; }
    }
}
