//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Attendees = new HashSet<Attendee>();
            this.Papers = new HashSet<Paper>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string encryptedPassword { get; set; }
        public int TitleId { get; set; }
        public string FullName { get; set; }
        public int GenderId { get; set; }
        public string Instituition { get; set; }
        public string Faculty { get; set; }
        public string Department { get; set; }
        public string ResearchField { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public int PostalCode { get; set; }
        public int CountryId { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public bool LoggedIn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendee> Attendees { get; set; }
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paper> Papers { get; set; }
        public virtual Title Title { get; set; }
    }
}
