// <auto-generated />
namespace ConferenceManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1004 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1004));
        
        string IMigrationMetadata.Id
        {
            get { return "201508251108518_1004"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
