//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagementSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConferenceManagementSystem.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {USER_TITLE}. {USER_NAME},&lt;br /&gt;&lt;br /&gt;&lt;/p&gt;
        ///&lt;p&gt;On behalf of the {CONF_SHORT} Committee, we are pleased to inform you that your submitted abstract ({PAPER_ID}) entitled &quot;{PAPER_TITLE}&quot;, has been accepted&amp;nbsp; for this conference. You are therefore requested to submit the extended abstract for Technical Reviewing process before&lt;strong&gt;{FULL_PAPER_DATE}&lt;/strong&gt;.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;http://submit.confbay.com/%7BPAPER_SUBMIT_LINK%7D&quot;&gt;Submit extended abstract no [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abstract_Acceptance {
            get {
                return ResourceManager.GetString("Abstract_Acceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {USER_TITLE}. {USER_NAME},&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;On behalf of the {CONF_NAME} Committee, we regret to inform you that your submitted abstract ({PAPER_ID}) entitled &quot;{PAPER_TITLE}&quot;, is not within the scope of this conference thus declined. We appreciate your effort and thank you for giving us the opportunity to view your work.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Again, thank you very much for your interest in this conference.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Best Regards,&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;{CONF_SHORT} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abstract_Rejection {
            get {
                return ResourceManager.GetString("Abstract_Rejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {USER_TITLE}. {USER_NAME},&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Thank you for submitting your abstract entitled &quot;{PAPER_TITLE}&quot;. Your reference number for this submission is &lt;strong&gt;{PAPER_ID}&lt;/strong&gt;. The abstract will be reviewed and result will be notified soonest possible.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;As a reminder, the {CONF_NAME} will be held on {CONF_TIME} at {CONF_VENUE}.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Please remember to quote the conference name and reference number in any form of communications with u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abstract_Submission {
            get {
                return ResourceManager.GetString("Abstract_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {USER_TITLE}. {USER_NAME},&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Congratulations. Your paper ({PAPER_ID}) entitled &quot;{PAPER_TITLE}&quot; has been accepted for presentation at the conference. As a confirmation, we hereby attached the final camera ready paper that you have submitted. The paper will be copy-edited for the official proceedings.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;We would like to remind you that the &lt;strong&gt;Conference Fee shall be paid 6 weeks before the conference date&lt;/strong&gt;. Failing to do so will result in ineligib [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Camera_Ready_Paper {
            get {
                return ResourceManager.GetString("Camera_Ready_Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {RVWR_TITLE}. {RVWR_NAME},&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;We have succesfully received your review of paper {PAPER_ID} entitled &quot;{PAPER_TITLE}&quot;. We thank you very much for your consideration and count on your assistance in making this {CONF_SHORT} a success.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Best Regards,&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;{CONF_SHORT} Administration&lt;br /&gt;Tel: {CONF_TELP}&lt;br /&gt;Fax: {CONF_FAX}&lt;br /&gt;Email: &lt;a href=&quot;mailto:%7BCONF_EMAIL%7D&quot;&gt;{CONF_EMAIL}&lt;/a&gt;&lt;br /&gt;Website: &lt;a href=&quot;http://submit.confbay [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Finish_Review {
            get {
                return ResourceManager.GetString("Finish_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {USER_TITLE}. {USER_NAME},&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Your Extended Abstract Submission for {PAPER_ID} is received. It will be sent to our appointed reviewers for comments.&lt;/p&gt;
        ///&lt;p&gt;&lt;br /&gt;As a confirmation of your submission, we hereby attached the full document file that you have submitted. The paper will be copy-edited for the official proceeding.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;As a reminder, the {CONF_NAME} will be held on {CONF_TIME} at {CONF_VENUE}.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Thank you for your s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Full_Paper_Submission {
            get {
                return ResourceManager.GetString("Full_Paper_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {USER_TITLE}. {USER_NAME},
        ///
        ///
        ///
        ///Congratulations. Your submission ({PAPER_ID}) entitled &quot;{PAPER_TITLE}&quot; has beenACCEPTED for presentation at the conference.
        ///
        ///
        ///
        ///You are therefore requested to submit &quot;Camera-ready paper&quot; before {CR_PAPER_DATE}.When submitting the camera-ready paper, make sure you follow STRICTLY the format of our conference proceedings.
        ///
        ///
        ///
        ///The reviewer&apos;s comments below, if any, are provided to assist you in preparing your camera-ready paper. You may submit your Camera Ready pape [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Paper_Acceptance {
            get {
                return ResourceManager.GetString("Paper_Acceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;{CONF_NAME}&lt;/strong&gt;&lt;/p&gt;
        ///&lt;hr /&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {RVWR_TITLE}. {RVWR_NAME},&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;This is concerning {CONF_SHORT} technical review. You have been assigned to review the selected extended abstract:&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Manuscript ID: {PAPER_ID}&lt;br /&gt;Title: {PAPER_TITLE}&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;For your information, we are scheduled to notify the authors about the acceptance/rejection of their papers on {PAPER_NOTIF_DATE}. Therefore, we would appreciate it v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Paper_For_Review {
            get {
                return ResourceManager.GetString("Paper_For_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {USER_TITLE}. {USER_NAME},&lt;/p&gt;
        ///&lt;p&gt;On behalf on the {CONF_SHORT} Committee, we regret to inform you that your submitted extended abstract ({PAPER_ID}) entitled &quot;{PAPER_TITLE}&quot;, has been declined for the conference as its review point did not fulfill the requirements.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;We appreciate your effort and thank you for giving us the opportunity to consider your work. We hope you plan to attend the {CONF_NAME}, and that you will consider submitting your work to future the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Paper_Rejection {
            get {
                return ResourceManager.GetString("Paper_Rejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {USER_TITLE}. {USER_GIVENNAME} {USER_SURNAME},&lt;br /&gt;&lt;br /&gt;We are pleased to inform you that your registration as {REGAS} for {CONF_NAME} ({CONF_SHORT}) has been CONFIRMED.&lt;/p&gt;
        ///&lt;p&gt;We look forward to seeing you and thank you for your support to {CONF_NAME}&lt;/p&gt;
        ///&lt;p&gt;Thank you. &lt;br /&gt;&lt;br /&gt;&lt;br /&gt;Yours sincerely,&lt;br /&gt;{CONF_NAME} ({CONF_SHORT})&lt;br /&gt;Tel: {CONF_TELP}&lt;br /&gt;Fax: {CONF_FAX}&lt;br /&gt;Email: {CONF_EMAIL}&lt;/p&gt;.
        /// </summary>
        internal static string Participant_Confirmation {
            get {
                return ResourceManager.GetString("Participant_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {USER_TITLE}. {USER_GIVENNAME} {USER_SURNAME},&lt;/p&gt;
        ///&lt;p&gt;Welcome to the {CONF_NAME} ({CONF_SHORT}) and thank you for your registration. Confirmation of this registration will only be made after full payment of registration fees.&lt;/p&gt;
        ///&lt;p&gt;Please remember to quote your registered name in the system in any form of communications with us.&lt;br /&gt;&lt;br /&gt;Thank you. &lt;br /&gt;&lt;br /&gt;&lt;br /&gt;Yours sincerely,&lt;br /&gt;{CONF_NAME} ({CONF_SHORT})&lt;br /&gt;Tel: {CONF_TELP}&lt;br /&gt;Fax: {CONF_FAX}&lt;br /&gt;Email: {CONF_EMAIL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Participant_Registration {
            get {
                return ResourceManager.GetString("Participant_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {USER_TITLE}. {USER_NAME},&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;We would like to thank you for your registration and welcome you to the&amp;nbsp; {CONF_NAME} ({CONF_SHORT}). The {CONF_NAME} will be held on {CONF_TIME} at {CONF_VENUE}.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;You are invited to submit your extended abstract for this conference, at the latest on {FULL_PAPER_DATE}.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Register / Login and &lt;a href=&quot;http://submit.confbay.com/%7BABSTRACT_SUBMIT_LINK%7D&quot;&gt;Submit your Abstract Now.&lt;br /&gt;&lt;/a&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Presenter_Registration {
            get {
                return ResourceManager.GetString("Presenter_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;INVITATION TO BECOME TECHNICAL REVIEWER FOR&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;{CONF_NAME}&lt;/strong&gt;&lt;/p&gt;
        ///&lt;hr /&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Dear {RVWR_TITLE}. {RVWR_NAME},&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;On behalf of the {CONF_NAME} - {CONF_SHORT} Technical Committee member, we would like to invite you to become one of the technical reviewers for this conference. Your commitment would be very much appreciated to ensure the highest standards in the quality of paper presented.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Your partic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Reviewer_Invitation {
            get {
                return ResourceManager.GetString("Reviewer_Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;/p&gt;.
        /// </summary>
        internal static string User_Invitation {
            get {
                return ResourceManager.GetString("User_Invitation", resourceCulture);
            }
        }
    }
}
